-- Item table

create table items(
    id int generated by default as identity (start with 1 increment by 1),
    published_date date not null,
    archived bool not null,
    primary key (id)
);

-- Label and Book tables (label is 1:m)
create table labels(
    id int generated by default as identity (start with 1 increment by 1),
    title varchar(255) not null,
    color varchar(255) not null,
    primary key (id)
);

create table books(
  id int,
  foreign key (id) references items(id),
  publisher varchar(255) not null,
  cover_state varchar(255) not null,
  primary key (id)
);

create table labels_items(
  label_id int,
  item_id int,
  foreign key (label_id) references labels(id),
  foreign key (item_id) references items(id)
);

CREATE INDEX ON labels_items (label_id);
CREATE INDEX ON labels_items (item_id);


-- Genre and Music Albums tables (genre is 1:m)
create table genres (
    id int generated by default as identity (start with 1 increment by 1),
    name varchar(255) not null,
    primary key (id)
);

create table musicalbums(
  id int,
  foreign key (id) references items(id),
  on_spotify bool not null,
  primary key (id)
);

create table genres_items(
  genre_id int,
  item_id int,
  foreign key (genre_id) references genres(id),
  foreign key (item_id) references items(id)
);

CREATE INDEX ON genres_items (genre_id);
CREATE INDEX ON genres_items (item_id);

-- Author and Games tables (author is 1:m)

create table authors(
    id int generated by default as identity (start with 1 increment by 1),
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    primary key (id)
);

create table games(
  id int,
  foreign key (id) references items(id),
  multiplayer varchar(255) not null,
  last_played_date date not null,
  primary key (id)
);

create table authors_items(
  author_id int,
  item_id int,
  foreign key (author_id) references authors(id),
  foreign key (item_id) references items(id)
);

-- Add genre, author and label tables to items table

alter table items
add column author_id,
add foreign key(author_id)
references authors(id);

alter table items
add column genre_id,
add foreign key(genre_id)
references genres(id);

alter table items
add column label_id,
add foreign key(label_id)
references labels(id);